#!/usr/bin/env bash
# HERMES BUILD HEARTBEAT — autogenerated
# Run: watch -n 30 ./heart.sh from any terminal to see if I'm alive.

SCRIPT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG="$SCRIPT/build.log"
HEART="$SCRIPT/heart.log"

echo "BUILD START: $(date -Iseconds) | PID: $$ | HOST: $(hostname)" > "$LOG"

while true; do
    echo "$(date '+%H:%M:%S') — HEARTBEAT — Last seen: $(tail -n1 $LOG 2>/dev/null | awk '{print $1, $2}' || echo 'never')" >> "$HEART"
    sleep 120
done
